chain_id = "testnet"
validators = 3
accounts = 2
binary = "provenance/build/provenanced"
hrp_prefix = "provenance"
denom = "hash"
coin_type = 505

[config_node.app]
minimum-gas-prices = "1905hash"
api = { enable = true, swagger = true, enabled-unsafe-cors = true }
rosetta = { enable = false }

[config_node.config]
instrumentation = { prometheus = false }
p2p = { addr_book_strict = false, allow_duplicate_ip = true }

[config_genesis.app_state.gov]
voting_params = { voting_period = "600s" }

[config_genesis.app_state.mint]
minter = { inflation = "0.300000000000000000" }
