name: Smoke test for Atomkraft

on:
  workflow_dispatch:

jobs:
  atomkraft-smoke-test:
    name: Atomkraft
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: Deps
        run: |
          pacman -Syu git python-poetry leveldb go --noconfirm --needed

      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Chain binary
        run: |
          (cd provenance; make build)

      - run: |
          poetry env use python
          . $(poetry env info -p)/bin/activate
          poetry install --no-root
          timeout 30s atomkraft chain testnet
